# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8082
    servlet:
        context-path: /generator
#url: jdbc:mysql://192.168.1.111:3306/gbp?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.110:3306/generator?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: sctv
        password: sctv
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
        static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

