spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      first:  #数据源1
        url: jdbc:mysql://192.168.0.182:3306/generator?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
      second:  #数据源2
        url: jdbc:mysql://192.168.0.182:3306/generator?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

map:
  file:
    local-dir: ./upload/file
    hdfs-dir: /data/csvType/upload
    err-data-dir: ./upload/err
    valid-data-dir: ./upload/valid
    date-type: yyyyMMdd HH:mm:ss,yyyyMMdd,yyyy-MM-dd HH:mm:ss,yyyy-MM-dd,yyyy-MM-dd HH:mm:ss,yyyy-MM-dd,yyyy/MM/dd HH:mm:ss,yyyy/MM/dd,MM/dd/yyyy,MM/dd/yyyy HH:mm:ss,yyyy\u5E74MM\u6708dd\u65E5HH\u65F6mm\u5206ss\u79D2,yyyy\u5E74MM\u6708dd\u65E5
  es:
    host: http://192.168.0.170
    port: 9200